### ISSUE TITLE
bugsnag-agent: Unsupported method ('OPTIONS')

### ISSUE THREAD

**Issue by sirajul147** [bugsnag/bugsnag-agent#19]
Hi,

I'm trying to set up a custom endpoint for bugsnag, by pointing my Javascript client, to a custom server, which have bugsnag client installed.

I've followed the documentation and set the config to listen to 0.0.0.0, so that I could call the endpoint from outside my server. It is up and running as expected.

I did a cUrl of the POST request and that is working as expected.

But the same is failing when I configure my Javascript client to point to the custom endpoint, in the OPTIONS call.

### Expected behavior
OPTIONS method should be handled, which will be fired prior tp POST method (used by ```bugsnag.notify``` method) from Javascript Client.

### Observed behavior

Error from bugsnag-agent:
```[21/May/2018 06:51:22] code 501, message Unsupported method ('OPTIONS')
[21/May/2018 06:51:22] "OPTIONS / HTTP/1.1" 501 -
```
Error in Browser:
![screen shot 2018-05-21 at 12 32 14 pm](https://user-images.githubusercontent.com/20811406/40294469-52f0c35a-5cf3-11e8-9a4e-168bdc7a4e92.png)

### Steps to reproduce
* Setup the agent as per the dcumentation.
* Configure the agent to listen to 0.0.0.0
* Configure the Javascript client to notify the errors to the new endpoint.
* Trigger an error and check error on browser and agent as well.

### Version
Agent: v1.2.0
JS Client: v4

### Additional information
*[Insert any additional information]*

#### Can't comment on Issues?
Some users have been unable to comment on Github issues when an [adblocker extension is enabled](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).
We recommend temporarily disabling the extension, or if that fails, contacting support@bugsnag.com.

**Comment by g1-diagnal** [comment]
@kattrali We are also facing the same issue. Any fixes available yet?
