### ISSUE TITLE
Daemonize bugsnag-agent

### ISSUE THREAD

**Issue by protoCall7** [bugsnag/bugsnag-agent#7]
Bugsnag agent should fork off to a daemon process, detach it's STDIN/STDOUT/STDERR, and use proper logging, thus allowing it to run as a daemon.

Once this is complete, a proper SysV init script, and possibly a systemd script should be provided.

**Comment by kattrali** [comment]
@protoCall7 Daemonizing makes sense, thank you for the suggestion.
