### ISSUE TITLE
Doesn't alleviate performance

### ISSUE THREAD

**Issue by aleemb** [bugsnag/bugsnag-agent#8]
Installing the agent yielded no network performance improvements for me. It turns out that PHP is not issuing a fire-and-forget and instead ends up waiting for the response from the agent but it could be something else, I am not sure.

Hopefully I am missing something obvious, any guidance would be appreciated.

The instrumentation is correct and the agent does log the incoming requests and they do show up on the bugsnag web app as well.

**Comment by aleemb** [comment]
After some poking around, it turns out this is because of curl behaviour.

For requests over 1024 bytes, curl automatically adds `Expect: 100-continue` which trips up the agent and the response is extremely slow. 

On the client-side this can be overcome by forcing a curl request over `HTTP/1.0` in the `bugsnag-php` lib which fixed things up. Or setting an empty header `"Except:"`.

**Comment by rafaelspecta** [comment]
In our case, Bugsnag does not work either with a huge amount of data (example 729k of json in the body). It also gets lost and error never reach the Bugsnag server, or reaches it incorrectly cause it is never shown in the interface. Same test with a smaller json works just fine.
We are using bugsnag with nodejs.

Can we change the title of this issue to something like:
"Bugsnag gets lost when request is big"

**Comment by GrahamCampbell** [comment]
We've fixed this issue with the PHP notifier regarding the expects header.

**Comment by rafaelspecta** [comment]
We are using bugsnag-node and it has this problem as well
github.com/bugsnag/bugsnag-node

**Comment by aleemb** [comment]
@rafaelspecta maybe open a new issue?
